/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.*;
import java.awt.TextField;
import javax.swing.JTextField;
/**
/**
 *
 * @author Jens
 */
public class Display extends javax.swing.JFrame implements ActionListener {
    
    private LimitHR_lower hrlower;
    private JTextField hrfield;      
    /**
     * Creates new form Monitor
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pulsoxi_panel = new javax.swing.JPanel();
        name_lab = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        surname_lab = new javax.swing.JLabel();
        birthday_lab = new javax.swing.JLabel();
        sexlab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        name_out = new javax.swing.JTextPane();
        patient_cng = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Heart_lab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        heartrate_out = new javax.swing.JTextPane();
        SPO2_lab = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        spo2_actout = new javax.swing.JTextPane();
        uperlim_lab = new javax.swing.JLabel();
        lowerlim_lab = new javax.swing.JLabel();
        spo2_lab = new javax.swing.JLabel();
        pulse_lower = new javax.swing.JTextField();
        pulse_upper = new javax.swing.JTextField();
        spo2_lower = new javax.swing.JTextField();
        reset_limit = new javax.swing.JButton();
        alarmbreak = new javax.swing.JButton();
        close = new javax.swing.JButton();
        header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name_lab.setText("Patient name:");

        surname_lab.setText("Patient surname:");

        birthday_lab.setText("Patient age:");

        sexlab.setText("Patient sex: ");

        jScrollPane1.setViewportView(name_out);

        patient_cng.setText("Change Patient");
        patient_cng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_cngActionPerformed(evt);
            }
        });

        Heart_lab.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Heart_lab.setText("Heart Rate");

        heartrate_out.setEditable(false);
        heartrate_out.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(heartrate_out);

        SPO2_lab.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        SPO2_lab.setText("SpO2");

        spo2_actout.setEditable(false);
        spo2_actout.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane3.setViewportView(spo2_actout);

        uperlim_lab.setText("Upper pulse limit");

        lowerlim_lab.setText("lower pulse limit");

        spo2_lab.setText("SpO2 Limit");

        pulse_lower.setEditable(false);
        pulse_lower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pulse_lowerMouseClicked(evt);
            }
        });
        pulse_lower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulse_lowerActionPerformed(evt);
            }
        });

        pulse_upper.setEditable(false);
        pulse_upper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pulse_upperMouseClicked(evt);
            }
        });
        pulse_upper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulse_upperActionPerformed(evt);
            }
        });

        spo2_lower.setEditable(false);
        spo2_lower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spo2_lowerMouseClicked(evt);
            }
        });
        spo2_lower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spo2_lowerActionPerformed(evt);
            }
        });

        reset_limit.setText("reset limits");
        reset_limit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_limitActionPerformed(evt);
            }
        });

        alarmbreak.setText("pause alarm");

        close.setText("Exit");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pulsoxi_panelLayout = new javax.swing.GroupLayout(pulsoxi_panel);
        pulsoxi_panel.setLayout(pulsoxi_panelLayout);
        pulsoxi_panelLayout.setHorizontalGroup(
            pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addComponent(Heart_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pulsoxi_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lowerlim_lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pulse_lower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uperlim_lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pulse_upper))
                        .addGap(81, 81, 81))
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexlab)
                                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                        .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(birthday_lab)
                                            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                                .addComponent(name_lab)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)))
                                        .addGap(82, 82, 82)
                                        .addComponent(surname_lab)))
                                .addGap(145, 145, 145)
                                .addComponent(patient_cng))
                            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(spo2_lab))
                                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(spo2_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)
                                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(alarmbreak, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(reset_limit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(52, Short.MAX_VALUE))))
            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(SPO2_lab)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pulsoxi_panelLayout.setVerticalGroup(
            pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_lab)
                    .addComponent(jLabel3)
                    .addComponent(surname_lab)
                    .addComponent(patient_cng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthday_lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexlab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Heart_lab))
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(close)))
                .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SPO2_lab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                .addComponent(lowerlim_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pulse_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                .addComponent(uperlim_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pulse_upper, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spo2_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pulsoxi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pulsoxi_panelLayout.createSequentialGroup()
                                .addComponent(reset_limit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alarmbreak))
                            .addComponent(spo2_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))))
        );

        header.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        header.setText("Pulsoximeter Vitaloverlord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header)
                    .addComponent(pulsoxi_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsoxi_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patient_cngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_cngActionPerformed
        close();
        disable_all();
        PatientData gui_data = new PatientData();
        gui_data.setVisible(true);
        // wait for return
        enable_all();   
    }//GEN-LAST:event_patient_cngActionPerformed

    private void pulse_lowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulse_lowerActionPerformed
        //get return insert to Button
        //pulse_lower.setText("blah");
    }//GEN-LAST:event_pulse_lowerActionPerformed

    private void pulse_upperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulse_upperActionPerformed
    }//GEN-LAST:event_pulse_upperActionPerformed

    private void spo2_lowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spo2_lowerActionPerformed
    }//GEN-LAST:event_spo2_lowerActionPerformed

    private void pulse_lowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulse_lowerMouseClicked
        close();
        disable_all();
        LimitHR_lower gui_lowerHR = new LimitHR_lower();
        gui_lowerHR.setVisible(true);
        // wait for return
        enable_all();
    }//GEN-LAST:event_pulse_lowerMouseClicked

    private void pulse_upperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulse_upperMouseClicked
        close();
        disable_all();
        LimitHR_upper gui_lowerHR = new LimitHR_upper();
        gui_lowerHR.setVisible(true);
        // wait for return
        enable_all();                  
    }//GEN-LAST:event_pulse_upperMouseClicked

    private void spo2_lowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spo2_lowerMouseClicked
        close();
        disable_all();
        LimitSPO2 gui_spo2 = new LimitSPO2();
        gui_spo2.setVisible(true);
        // wait for return
        enable_all();   
    }//GEN-LAST:event_spo2_lowerMouseClicked

    private void reset_limitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_limitActionPerformed
        disable_all();
        ResetLimits gui_resetlim = new ResetLimits();
        gui_resetlim.setVisible(true);
    }//GEN-LAST:event_reset_limitActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        systemclose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Setlimitstartup setlimit = new Setlimitstartup();
                setlimit.setVisible(true);
                
                // wait for return
                new Display().setVisible(true);
                //disable_all();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heart_lab;
    private javax.swing.JLabel SPO2_lab;
    private javax.swing.JButton alarmbreak;
    private javax.swing.JLabel birthday_lab;
    private javax.swing.JButton close;
    private javax.swing.JLabel header;
    private javax.swing.JTextPane heartrate_out;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lowerlim_lab;
    private javax.swing.JLabel name_lab;
    private javax.swing.JTextPane name_out;
    private javax.swing.JButton patient_cng;
    private javax.swing.JTextField pulse_lower;
    private javax.swing.JTextField pulse_upper;
    private javax.swing.JPanel pulsoxi_panel;
    private javax.swing.JButton reset_limit;
    private javax.swing.JLabel sexlab;
    private javax.swing.JTextPane spo2_actout;
    private javax.swing.JLabel spo2_lab;
    private javax.swing.JTextField spo2_lower;
    private javax.swing.JLabel surname_lab;
    private javax.swing.JLabel uperlim_lab;
    // End of variables declaration//GEN-END:variables
    
    private void close()
    {
        Display gui_monitor = new Display();
        gui_monitor.setVisible(false);
    }
    private void systemclose(){
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseing);
    }
    private void disable_all(){
        pulse_lower.setEnabled(false);
        pulse_upper.setEnabled(false);
        spo2_lower.setEnabled(false);
        patient_cng.setEnabled(false);
    }
    private void enable_all(){
        pulse_lower.setEnabled(true);
        pulse_upper.setEnabled(true);
        spo2_lower.setEnabled(true);
        patient_cng.setEnabled(true);
    }

    public void updatehr(LimitHR_lower hrlower){
        this.hrlower = hrlower;
        this.hrfield = hrlower.savelowerhr();
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
