
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jens
 */
public class PatientData extends javax.swing.JFrame {
    private JTextField patientfield = new JTextField();        
    private String[] items = {"male", "female"};
    
    /**
     * Creates new form PatData
     */
    public PatientData() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Patientdata_UI = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        savepatient = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        surname = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        birthdate = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        surname_field = new javax.swing.JTextField();
        sex_box = new javax.swing.JComboBox<>();
        dd = new javax.swing.JSpinner();
        MM = new javax.swing.JSpinner();
        yyyy = new javax.swing.JSpinner();
        Patient_data_heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        name.setText("Patient name:");

        savepatient.setText("save");
        savepatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepatientActionPerformed(evt);
            }
        });

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        surname.setText("Patient surname:");

        sex.setText("Patient sex: ");

        birthdate.setText("Patient birthdate:");

        name_field.setText("insert name");
        name_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name_fieldMouseClicked(evt);
            }
        });
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });

        surname_field.setText("instert surname");
        surname_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surname_fieldMouseClicked(evt);
            }
        });
        surname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_fieldActionPerformed(evt);
            }
        });

        sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        sex_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex_boxActionPerformed(evt);
            }
        });

        dd.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        MM.setModel(new javax.swing.SpinnerNumberModel(1, 0, 12, 1));

        yyyy.setModel(new javax.swing.SpinnerNumberModel(2018, 1920, 3000, 1));

        Patient_data_heading.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Patient_data_heading.setText("Insert Patient data");

        jLabel1.setText("Day");

        jLabel2.setText("Month");

        jLabel3.setText("Year");

        javax.swing.GroupLayout Patientdata_UILayout = new javax.swing.GroupLayout(Patientdata_UI);
        Patientdata_UI.setLayout(Patientdata_UILayout);
        Patientdata_UILayout.setHorizontalGroup(
            Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patientdata_UILayout.createSequentialGroup()
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Patientdata_UILayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Patient_data_heading))
                    .addGroup(Patientdata_UILayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(surname)
                            .addComponent(sex)
                            .addComponent(birthdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_field)
                            .addComponent(surname_field)
                            .addComponent(sex_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Patientdata_UILayout.createSequentialGroup()
                                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Patientdata_UILayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel1)))
                                .addGap(12, 12, 12)
                                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Patientdata_UILayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yyyy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Patientdata_UILayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24))))
                            .addGroup(Patientdata_UILayout.createSequentialGroup()
                                .addComponent(savepatient, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Patientdata_UILayout.setVerticalGroup(
            Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Patientdata_UILayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Patient_data_heading)
                .addGap(18, 18, 18)
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surname)
                    .addComponent(surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sex)
                    .addComponent(sex_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdate)
                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Patientdata_UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(savepatient))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Patientdata_UI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Patientdata_UI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
            close();
	}//GEN-LAST:event_cancelActionPerformed

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        String name = name_field.getText();
        checkdata(name);
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void sex_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sex_boxActionPerformed

    private void savepatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepatientActionPerformed
        String name = name_field.getText();
        checkdata(name);
        
        String surname = surname_field.getText();
        checkdata(surname);
        
        // Get name and surname
        // check name/surname = default 
        // check name/surname = numeric
        // else return name/surname;
        
        close();
    }//GEN-LAST:event_savepatientActionPerformed

    private void surname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_fieldActionPerformed
        String surname = surname_field.getText();
        checkdata(surname);
    }//GEN-LAST:event_surname_fieldActionPerformed

    private void name_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_fieldMouseClicked
        name_field.setText("");
    }//GEN-LAST:event_name_fieldMouseClicked

    private void surname_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surname_fieldMouseClicked
        surname_field.setText("");
    }//GEN-LAST:event_surname_fieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner MM;
    private javax.swing.JLabel Patient_data_heading;
    private javax.swing.JPanel Patientdata_UI;
    private javax.swing.JLabel birthdate;
    private javax.swing.JButton cancel;
    private javax.swing.JSpinner dd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_field;
    private javax.swing.JButton savepatient;
    private javax.swing.JLabel sex;
    private javax.swing.JComboBox<String> sex_box;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField surname_field;
    private javax.swing.JSpinner yyyy;
    // End of variables declaration//GEN-END:variables
    
    public  boolean checkdata(String name){               
        if (name.contains("[0-9]+")==true){
            JOptionPane.showMessageDialog(new JFrame(), "Name darf keine Zahlen enthalten","Warnung",JOptionPane.ERROR_MESSAGE);
        }
        return false;
        //abfrage ob namens text zahlen enthält
    }
    
    private void close()
    {
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseing);
    }
}