
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jens
 */
public class Setlimitstartup extends javax.swing.JFrame {
        
    Display main;
    /**
     * Creates new form Setlimits
     */
    public Setlimitstartup(Display display) {
        initComponents();
        this.main = display;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upper_label = new javax.swing.JLabel();
        upper_hr = new javax.swing.JTextField();
        spo2_value = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lower_hr = new javax.swing.JTextField();
        lower_label2 = new javax.swing.JLabel();
        setlimits = new javax.swing.JButton();
        restoredefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        upper_label.setText("Insert upper Pulse alarm Limit");

        upper_hr.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        upper_hr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        upper_hr.setText("180");
        upper_hr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upper_hrMouseClicked(evt);
            }
        });
        upper_hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upper_hrActionPerformed(evt);
            }
        });

        spo2_value.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        spo2_value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spo2_value.setText("90");
        spo2_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spo2_valueMouseClicked(evt);
            }
        });
        spo2_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spo2_valueActionPerformed(evt);
            }
        });

        jLabel1.setText("Insert SpO2 alarm Limit");

        lower_hr.setBackground(new java.awt.Color(245, 245, 245));
        lower_hr.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lower_hr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lower_hr.setText("50");
        lower_hr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lower_hr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lower_hrMouseClicked(evt);
            }
        });
        lower_hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lower_hrActionPerformed(evt);
            }
        });

        lower_label2.setText("Insert lower Pulse alarm Limit");

        setlimits.setText("save limits");
        setlimits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setlimitsActionPerformed(evt);
            }
        });

        restoredefault.setText("restore default limits");
        restoredefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoredefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spo2_value, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lower_hr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lower_label2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restoredefault)
                                    .addComponent(setlimits, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upper_label)
                                    .addComponent(upper_hr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upper_label)
                            .addComponent(lower_label2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upper_hr, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lower_hr, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spo2_value, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setlimits)
                        .addGap(18, 18, 18)
                        .addComponent(restoredefault)
                        .addGap(26, 26, 26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upper_hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upper_hrActionPerformed
        String upperfieldvalue = upper_hr.getText();
        try {
            int upperhr = Integer.parseInt( upperfieldvalue );
            if (upperhr < 80 || upperhr >= 300) {
                JOptionPane.showMessageDialog(new JFrame(), "Nur Werte zwischen 120 und 300 sind gültig","Warnung",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch( Exception e )
        {
            JOptionPane.showMessageDialog(new JFrame(), "Eingegebener Wert ist keine gültige Zahl","Warnung",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_upper_hrActionPerformed

    private void spo2_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spo2_valueActionPerformed
        String spo2_val = spo2_value.getText();      
        try {
            int spo2_int = Integer.parseInt( spo2_val );
            if (spo2_int < 60 || spo2_int >= 100) {
                JOptionPane.showMessageDialog(new JFrame(), "Nur Werte zwischen 60 und 100 sind gültig","Warnung",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch( Exception e )
        {
            JOptionPane.showMessageDialog(new JFrame(), "Eingegebener Wert ist keine gültige Zahl","Warnung",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_spo2_valueActionPerformed

    private void lower_hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lower_hrActionPerformed
        String lowerfiledvalue = lower_hr.getText();
        try {
            int lowerhr = Integer.parseInt( lowerfiledvalue );
            if (lowerhr < 20 || lowerhr >= 160) {
                JOptionPane.showMessageDialog(new JFrame(), "Nur Werte zwischen 20 und 160 sind gültig","Warnung",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch( Exception e )
        {
            JOptionPane.showMessageDialog(new JFrame(), "Eingegebener Wert ist keine gültige Zahl","Warnung",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_lower_hrActionPerformed

    private void setlimitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setlimitsActionPerformed
        String lowhr = lower_hr.getText();
        String uphr = upper_hr.getText();
        String spo2 = spo2_value.getText();
        
        boolean ch = main.check_init(uphr, lowhr, spo2); 
        if (ch == true){
            main.updatelimit(lowhr,uphr,spo2);
            main.setVisible(true);  
            close();
        }
        else{
            JOptionPane.showMessageDialog(new JFrame(), "Bitte gültige Werte eingeben","Warnung",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_setlimitsActionPerformed

    private void restoredefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoredefaultActionPerformed
        lower_hr.setText("50");
        upper_hr.setText("180");
        spo2_value.setText("90");
    }//GEN-LAST:event_restoredefaultActionPerformed

    private void lower_hrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lower_hrMouseClicked
        lower_hr.setText("");
    }//GEN-LAST:event_lower_hrMouseClicked

    private void upper_hrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upper_hrMouseClicked
        upper_hr.setText("");
    }//GEN-LAST:event_upper_hrMouseClicked

    private void spo2_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spo2_valueMouseClicked
        spo2_value.setText("");
    }//GEN-LAST:event_spo2_valueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setlimitstartup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setlimitstartup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setlimitstartup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setlimitstartup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lower_hr;
    private javax.swing.JLabel lower_label2;
    private javax.swing.JButton restoredefault;
    private javax.swing.JButton setlimits;
    private javax.swing.JTextField spo2_value;
    private javax.swing.JTextField upper_hr;
    private javax.swing.JLabel upper_label;
    // End of variables declaration//GEN-END:variables

    private void close()
    {
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseing);
    }
}
